### ISSUE TITLE
Dashboard is slow to connect

### ISSUE THREAD

**Issue by r4stered** [frc-web-components/app#19]
Hello,

I really like FRC web components and the app that goes with it. However, during our competition this past week, the app itself was very slow to connect to the robot compared to other dashboards such as Shuffleboard, Smartdashboard etc. We had a match where we couldn't change our auto mode to the correct one before the match started. After switching to SmartDashboard with no other changes, it showed the status as connected much faster.

**Comment by amorygalili** [comment]
Hi @r4stered, thanks for for opening up this issue! My team was experiencing something like this as well at our competition last week, although fortunately we always connected before the match started. I'll look into this more tomorrow when I have access to a robot and will get back to you.

**Comment by amorygalili** [comment]
@r4stered did your team only observe this happening during matches, or were you also having trouble connecting while testing or running the sim?

**Comment by r4stered** [comment]
Just tested with sim, and it connects basically instantly. I can test with an "at home" configured radio and robot within the next couple days as I just got back from competition, but from what I remember it seems to connect pretty quick at home.

**Comment by amorygalili** [comment]
@r4stered were you connecting to the robot with a team # (e.g. 1234) instead of an IP (e.g. 10.12.34.2)? Asking since when you enter a team number it uses mDNS which might be slow to respond at competitions. Other dashboards like glass and shuffleboard  try to connect to the following addresses and then choose the one that connects first:

```
10.TE.AM.2
172.22.11.2
roborio-TEAM-FRC.local
roborio-TEAM-FRC.lan
roborio-TEAM-FRC.frc-field.local
```

I'll be taking this approach. In the meantime I would use the `10.TE.AM.2` format until the issue is fixed. It shouldn't take too long but it's something you'd probably need to do if you have a competition this weekend.

**Comment by amorygalili** [comment]
@r4stered I just created a new release with a fix: https://github.com/frc-web-components/app/releases/tag/app-v0.4.1 It's hard to verify the change until I'm at an actual competition. I've also had limited time to test this on a robot, so I would be prepared to roll back just in case the new release gives you problems. Let me know if you run into any issues.
